name: "Docs Check"
on:
  - pull_request
  - push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: python -m pip install --upgrade -r requirements.txt
          docs-folder: "doc-source/"
